#!/usr/bin/env bash
# Display information about subdomains.

get_record_info() {
    local domain="$1"
    local subdomain="$2"
    local record_info=$(dig +short -t A $subdomain.$domain | awk '{print "The subdomain " "'$subdomain'" " is a A record and points to " $1}')
    echo "$record_info"
}

domain="$1"
subdomain="$2"

if [ -z "$subdomain" ]; then
    subdomains=("www" "lb-01" "web-01" "web-02")
else
    subdomains=("$subdomain")
fi

for subdomain in "${subdomains[@]}"; do
    get_record_info "$domain" "$subdomain"
done
