#!/usr/bin/env bash
# Configures a Nginx server so that /redirect_me is redirecting to another page.

sudo apt-get update
sudo apt-get -y install nginx

echo 'Hello World!' | sudo tee /var/www/html/index.html

echo 'server {
    listen 80;
    server_name _;

    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }
}' | sudo tee /etc/nginx/sites-available/redirect_me

sudo ln -s /etc/nginx/sites-available/redirect_me /etc/nginx/sites-enabled/

sudo service nginx restart
