#!/usr/bin/env bash
# Configures a Nginx server so that /redirect_me is redirecting to another page.

sudo apt-get update
sudo apt-get -y install nginx

echo 'Hello World!' | sudo tee /var/www/html/index.html

cat > /etc/nginx/sites-available/default <<EOL
server {
    listen 80;
    server_name _;

    location / {
        root /var/www/html;
    }

    location /redirect_me {
        return 301 https://youtube.com/watch?v=QH2-TGUlwu4;
    }
}
EOL

sudo nginx -s reload
sudo service nginx restart
