#!/usr/bin/env bash
# Configures a Nginx server so that /redirect_me is redirecting to another page.

sudo apt-get -y update
sudo apt-get -y install nginx

sudo ufw allow 'Nginx HTTP'

echo 'Hello World!' | sudo tee /var/www/html/index.html

sudo sed -i '/listen 80 default_server;/a \
     location /redirect_me {\
     	      rewrite ^/redirect_me https://youtube.com/ permanent;\
     }' /etc/nginx/sites-available/default

echo "Ceci n'est pas une page" | sudo tee /var/www/html/custom_404.html > /dev/null

sudo sed -i '/#error_page 404 \/404.html;/ {
     s|#error_page 404 /404.html;|error_page 404 /custom_404.html;|
}' /etc/nginx/sites-available/default

sudo service nginx restart
