#!/usr/bin/env bash
# Configures Nginx servers to have a custom HTTP response header

# Update package list and install Nginx
sudo apt-get update
sudo apt-get -y install nginx

# Set the custom header name and value
HEADER_NAME="X-Served-By"
HEADER_VALUE=$(hostname)  # Gets the hostname of the server

# Create a custom HTML page with the hostname
echo "Hello World! This is $(hostname)" | sudo tee /var/www/html/index.html

# Configure Nginx default site with custom header
cat > /etc/nginx/sites-available/default <<EOL
server {
    listen 80;
    server_name _;

    location / {
        root /var/www/html;
        add_header $HEADER_NAME $HEADER_VALUE;
    }

    location /redirect_me {
        return 301 https://youtube.com/watch?v=QH2-TGUlwu4;
    }

    error_page 404 /404.html;
    location = /404.html {
        root /var/www/html;
        internal;
    }
}
EOL

# Create a custom 404 page
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html

# Reload Nginx to apply changes
sudo nginx -s reload
sudo service nginx restart
