#!/usr/bin/env bash

# Update package list and install HAProxy
sudo apt-get update
sudo apt-get -y install haproxy

# Configure HAProxy
sudo tee /etc/haproxy/haproxy.cfg > /dev/null <<'EOF'
global
    daemon
    maxconn 256

defaults
    mode http
    timeout connect 5000ms
    timeout client 50000ms
    timeout server 50000ms

frontend http-in
    bind *:80
    default_backend servers

backend servers
    balance roundrobin
    server 318409-web-01 54.236.45.64:80 check
    server 318409-web-02 54.84.213.70:80 check
EOF

# Enable HAProxy init script management
sudo sed -i 's/ENABLED=0/ENABLED=1/' /etc/default/haproxy

# Restart HAProxy service
sudo service haproxy restart
