#!/usr/bin/env bash
#Process and PID file
function sig_term() {
    echo "I hate the kill command"
}

function sig_int() {
    echo "Y U no love me?!"
}

function sig_quit() {
    rm -f /var/run/myscript.pid
    exit 0
}

trap 'sig_term' SIGTERM
trap 'sig_int' SIGINT
trap 'sig_quit' SIGQUIT SIGTERM

echo $$ > /var/run/myscript.pid

while true; do
    echo "To infinity and beyond"
    sleep 2
done
