#!/usr/bin/env bash
# A script that displays infinity and beyond
function invincible() {
    echo "I am invincible!!!"
}

trap invincible SIGTERM

while true; do
    echo "To infinity and beyond"
    sleep 2
done
