#!/usr/bin/env bash
# Displays the content of the file /etc/passwd, using the while loop + IFS

while IFS=: read -r username password uid gid user_info homedir shell; do
    echo "The user $username is part of the $gid gang, lives \
in $homedir and rides $shell. $uid's place is \
protected by the passcode $password, more info about \
the user here: $user_info"
done < /etc/passwd
