#!/usr/bin/env bash
# script that displays Best School 10 times, and hi on the 9th iteration
num=1
while [ $num -le 10 ]; do
      echo "Best School"
      if [ $num -eq 9 ]; then
      	 echo "Hi"
      fi
      (( num++ ))
done
